//Copyright (c) 2016 by Cisco Systems, Inc. All rights reserved.
package com.cisco.iotsp.sample;

import java.io.File;
import java.util.List;
import java.util.Map;

import com.cisco.iotsp.client.schemas.model.SchemaCreateRequest;
import com.cisco.iotsp.client.things.ApiException;
import com.cisco.iotsp.client.things.ThingsApi;
import com.cisco.iotsp.client.things.model.SectionSchemaPair;
import com.cisco.iotsp.client.things.model.Thing;
import com.cisco.iotsp.client.things.model.ThingCreateRequest;
import com.cisco.iotsp.client.things.model.ThingIdentifier;
import com.cisco.iotsp.client.things.model.ThingUpdateRequest;
import com.cisco.iotsp.helper.JsonHelper;
import com.cisco.iotsp.helper.ServiceApiHelper;
import com.fasterxml.jackson.databind.ObjectMapper;

public class SampleThingsCreate {
	private ThingsApi api;

	public SampleThingsCreate(String serviceAddr, String accessToken) {
		System.out.println(String.format("Sample client for iot-thing-registry at %s", serviceAddr));

		api = ServiceApiHelper.getThingsApi(serviceAddr, accessToken);
	}

	public Thing createThingFromJsonFile(String accountAlias, String thingFilePathInResources) {
		try {
			ObjectMapper mapper = new ObjectMapper();			
			ThingCreateRequest newRequest = mapper.readValue(ClassLoader.getSystemResourceAsStream(thingFilePathInResources), ThingCreateRequest.class);
			
			//The file thingFilePathInResources contains symbolic schema uid in the format of accountAlias~region~schemaName,  with region as empty
			//Replace the string "accountAlias" with actual account alias, to get the schema uid generated by the system. 
			for (SectionSchemaPair section : newRequest.getSectionSchemas()) {
				String schemaUid =  section.getSchemaUid().replaceFirst("accountAlias", accountAlias);	
				section.setSchemaUid(schemaUid);
			}
			
			//User can assign a uid (must be unique) to the new Thing object
			//The Thing Uid must be in the format of accountAlias~region~id.  Region is empty string for now
			//If user does not assign uid in createThing request, then system will assign a uid
			String region = "";
			newRequest.setUid(accountAlias + "~" + region  + "~" + "MyUniqueyDeviceUid");
			System.out.printf("\n createThing, request is: %s", newRequest);
			Thing newThing = api.createThing(newRequest);

			if (newThing != null) {
				System.out.println("\n--- createThingFromJsonFile is successful: ---");
				System.out.println(newThing);
			} else
				System.out.println("\n--- createThingFromJsonFile failed! ---");

			return newThing;
		} catch (ApiException apiE) {
			System.out.printf("\n--- createThingFromJsonFile failed !!! ---");
			System.out.printf("\ncode=%d\n msg=%s\n header=%s\n body=%s\n", apiE.getCode(), apiE.getMessage(),
					apiE.getResponseHeaders(), apiE.getResponseBody());
			System.out.println(apiE);
			apiE.printStackTrace();
			return null;

		} catch (Exception e) {
			System.out.printf("\n--- createThingFromJsonFile failed !!! ---");
			System.out.println(e);
			e.printStackTrace();
			return null;
		}
	}

}
