package com.cisco.iotsp.helper;

import java.util.Locale;
import java.util.Map;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import com.cisco.iotsp.client.accounts.model.AccountAdminUser;
import com.cisco.iotsp.client.accounts.model.AccountCreateObject;
import com.cisco.iotsp.client.accounts.model.AccountCreateObject.AccountTypeEnum;

public class AccountHelper {

	// Create an account and returns account Uid that is generated by Cisco
	// IOTSP Accounts service
	public static String createAccount(String serviceAddress, String accountAlias, String accountName,
			String accountType, String adminFirstName, String adminLastName, String adminPassWd, String adminEmail) {
		String apiBasePath = "https://" + serviceAddress;
		AccountTypeEnum type = AccountTypeEnum.valueOf(accountType.toUpperCase(Locale.ENGLISH));
		AccountCreateObject request = new AccountCreateObject();
		request.setAccountType(type);
		request.setName(accountName);
		request.setAlias(accountAlias);
		AccountAdminUser adminUser = new AccountAdminUser();
		adminUser.setFirstName(adminFirstName);
		adminUser.setLastName(adminLastName);
		adminUser.setEmailAddress(adminEmail);
		adminUser.setPassword(adminPassWd);
		request.setAccountAdminUser(adminUser);
		String input = JsonHelper.convertPojoToJsonString(request);

		String url = String.format("%s/v1/user-services/accounts", apiBasePath);

		Client client = ClientHelper.createClient();
		WebTarget webTarget = client.target(url);

		System.out.println(url);
		System.out.println("Payload to create account: ");
		System.out.println(input);

		Invocation.Builder invocationBuilder = webTarget.request(MediaType.APPLICATION_JSON);
		Response response = invocationBuilder.post(Entity.entity(input, MediaType.APPLICATION_JSON));

		System.out.printf("--- Create Account --- Status: %d --- ", response.getStatus());
		System.out.println("Headers:");
		System.out.println(response.getHeaders());

		System.out.println(response);
		System.out.println("Output from Server .... \n");
		String output = response.readEntity(String.class);
		System.out.println(output);

		Map<String, Object> map = JsonHelper.convertJsonStringToMap(output);

		System.out.println("Create account is finished.");
		System.out.println(map);

		String accountUid = map.get("uid").toString();
		return accountUid;
	}

}
